###
GET http://localhost:8080/movies

###
GET http://localhost:8080/movies/6652a65d38127ce9769e4c72

###
POST http://localhost:8080/movies
Content-Type: application/json
{
  "title": "Mulan",
  "release_year": 1998,
  "genre": ["Animation", "Adventure"],
  "director": "Tony Bancroft, Barry Cook",
  "rating": 7.6
}


PUT http://localhost:8080/movies/{movieId}
Content-Type: application/json
{
  "title": "Mulan",
  "release_year": 1998,
  "genre": ["Animation", "Adventure", "Family"],
  "director": "Tony Bancroft, Barry Cook",
  "rating": 8.0
}

DELETE http://localhost:8080/movies/{movieId}

______________RENDER___________________________
### Get all movies
GET https://viddevil.onrender.com/movies

###

### Get a movie by ID
GET https://viddevil.onrender.com/movies/6652a65d38127ce9769e4c71

###

### Create a new movie
POST https://viddevil.onrender.com/movies
Content-Type: application/json

{
  "title": "Mulan",
  "release_year": 1998,
  "genre": ["Animation", "Adventure", "Family"],
  "director": "Tony Bancroft, Barry Cook",
  "rating": 7.6
}

###

### Update a movie by ID
PUT https://viddevil.onrender.com/movies/6658d3e66fbdad9fc2c8d847
Content-Type: application/json

{
  "title": "test",
  "release_year": 1998,
  "genre": ["Animation", "Adventure", "Family"],
  "director": "Tony Bancroft, Barry Cook",
  "rating": 8.0
}

###

### Delete a movie by ID
DELETE https://viddevil.onrender.com/movies/6658d3e66fbdad9fc2c8d847
